name: test
on:
  push:
    branches:
    - "master"
  pull_request: {}
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macOS-latest
        - windows-latest
        go:
        - '1.15'
    name: Go ${{ matrix.go }} Test
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: setup go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - name: test
      run: go test -v